### ISSUE TITLE
Qemu-GA 

### ISSUE THREAD

**Issue by kaganisildak** [LordNoteworthy/al-khaser#105]
I think qemu-ga.exe should be added to the "Processes" section
https://any.run/

Any.Run is an "amas"(automated malware analysis system). qemu-ga.exe is a agent of qemu virt. system.

**Comment by kaganisildak** [comment]
sorry, qemu-ga.exe

**Comment by LordNoteworthy** [comment]
Thank you so much for reporting this, it was merged to master: 

#106
