### ISSUE TITLE
disk_size_wmi acting weird with llVal

### ISSUE THREAD

**Issue by Hemorragie** [LordNoteworthy/al-khaser#111]
Hi everyone,

I tried your solution in order to create an hidden Qemu/KVM Sandbox. But when i tried your program on Windows 7 64 bits with the al-khaser_x64.exe i never pass the flag "Checking hard disk size using WMI".
So i looked at the code and make my partition up to 90GB and it still not pass.
I reproduced your code with the MSDN and figured out that you use the parameter vtProp.llVal in order to get the size of the disk. But when i do the same llVal send me random values each time I launch the program. Instead I used the parameter bstrVal which give the exact amount of Bytes on the disk.

I also have to mention that with the x86.exe the "Checking hard disk size using WMI" pass everytime.

**Comment by LordNoteworthy** [comment]
Hello @Hemorragie 

Thanks for reporting this, I will check this by today and report back to you. Seems it is an issue as you said.

**Comment by gsuberland** [comment]
Fixed. Thanks for the report.
