### ISSUE TITLE
Any way detect CE VEH debugger/page exceptions?

### ISSUE THREAD

**Issue by friuns2** [LordNoteworthy/al-khaser#129]
any way detect CE VEH debugger/page exceptions?

"TLS thread attach callback" also seems work for me in reverse logic. It returns Bad for me if nothing attached but if i attach VEH debugger it returns Good for me. Not sure if its related

**Comment by gsuberland** [comment]
Page exception breakpoints can be detected by walking VirtualQuery over the module's .text address space, but I suspect that if the "Try to hide debugger" checkbox is ticked CE will hook these and fake the results (I'm not 100% sure though). I'll add this to the pipeline.

Regarding the TLS thread attach, please try building from the latest source as I recently changed that check's code. If the issue persists it's probably better if you open a new ticket so we can fix that separately.

**Comment by gsuberland** [comment]
It seems that CE does something clever with VirtualQuery to lie about pages' guard/noaccess status when such BPs are in use, which invalidates my original approach.

However it is possible to instead do an initial enumeration of the executable pages in the process and re-scan them again later to see if they're still executable. This has the downside of not catching page BPs set early on (i.e. before the initial enumeration of pages) but it does catch cases where any new page BP is set after the enumeration.

I've written code that takes both approaches. It enumerates page states at startup, then at the time of the check it looks for guard/noaccess pages in the module (old approach) and then does a query and compare on the pages that were found in the first step.

PR merged and closed.

**Comment by gsuberland** [comment]
I'll open a second issue for VEH debugger detection. I also ran into another way to detect CE while debugging this trick.

**Comment by friuns2** [comment]
> It seems that CE does something clever with VirtualQuery to lie about pages' guard/noaccess status when such BPs are in use, which invalidates my original approach.

@gsuberland is there way to detect API hooking?

**Comment by gsuberland** [comment]
Yes, and I'm working on it.

The first way is easy (see if the pointer given from GetProcAddress is within the bounds of the module) but a clever hook can bypass the check.

The second way involves parsing PE files on disk, enumerating the exports table, grabbing the first few bytes of code from each export, applying relocation fixups, then comparing to the entry point of the API in memory. It'll catch out detours and code-cave approaches where GetProcAddress still returns the original function address but that function's EP has been replaced with a trampoline.

**Comment by friuns2** [comment]
cool, looking forward :)

**Comment by gsuberland** [comment]
Implemented the first type of check in #138.
