### ISSUE TITLE
TLS thread attach callback getting false positive

### ISSUE THREAD

**Issue by friuns2** [LordNoteworthy/al-khaser#130]
I built commit 350631a and I get TLS thread attach callback as Bad, no debuggers attached
Windows 7 x64 Administator account
here is full log
https://gist.github.com/friuns2/9c5a72935972b291a82e93bff4cd7f70

**Comment by gsuberland** [comment]
Interesting that it passes process attach but not thread attach. I've added some debug output to the code to help diagnose your issue. Please recompile with the latest code, run [DbgView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview), then run Al-Khaser and see what debug data comes out in the log.

**Comment by friuns2** [comment]
[14236] All seems fine for TLSCallbackProcess.
[14236] TLSCallbackThread timeout on event wait.

[*] TLS process attach callback
                   [ GOOD ]
[*] TLS thread attach callback
                   [ BAD  ]

**Comment by gsuberland** [comment]
Interesting that it seems to find the callback event handle but fails on waiting for the event itself.

I've added a couple of extra lines of output in 9d962ad. Can you give it another run?

**Comment by friuns2** [comment]
[11488] TLS callback: process attach
[11488] All seems fine for TLSCallbackProcess.
[11488] TLSCallbackThread timeout on event wait.
[11488] TLS callback: thread attach
[11488] TLS callback: thread attach
[11488] TLS callback: thread attach

**Comment by friuns2** [comment]
Ok now both are Good

**Comment by gsuberland** [comment]
Nice!
