### ISSUE TITLE
Should i do TLS checks in a while loop or only at application launch?

### ISSUE THREAD

**Issue by friuns2** [LordNoteworthy/al-khaser#134]
Should i do TLS checks in a while loop or only at application launch?

i tried put TLS checks in a while loop, then something goes wrong it freezes for 4 seconds and returns true

first interation
0 TLS process attach callback   (36 ms)
0 TLS thread attach callback   (154 ms)

second interation
1 TLS process attach callback   (4999843 ms)
0 TLS thread attach callback   (435 ms)

**Comment by gsuberland** [comment]
Only once. The idea is to catch the TLS callback set in the PE header. Looping it offers no additional protection.

**Comment by friuns2** [comment]
ok thanks
