### ISSUE TITLE
check vtProp.vt == VT_BSTR before accessing vtProp.bstrVal

### ISSUE THREAD

**Issue by hzqst** [LordNoteworthy/al-khaser#149]
![1](https://user-images.githubusercontent.com/12287588/44774320-6e1abe00-aba5-11e8-8193-828ac4d2f4c0.png)

Crashed in `serial_number_bios_wmi` since `hRes = pclsObj->Get(_T("SerialNumber"), 0, &vtProp, 0, 0);`  failed and we got an invalid vtProp here, which is accessed later `StrStrI(vtProp.bstrVal, _T("VMWare")) != 0)`

A quick fix is to check if hres is S_OK and vtprop.vt is BT_STR `if (hRes == S_OK && vtProp.vt == VT_BSTR)
				` before doing the string comparaison.

**Comment by LordNoteworthy** [comment]
Hello @hzqst 

Thanks for reporing the issue, will fix it in the PR 👍

**Comment by gsuberland** [comment]
Looks like this was fixed in cb88612.
