### ISSUE TITLE
Problem in function "serial_number_bios_wmi()".

### ISSUE THREAD

**Issue by SanseoLab** [LordNoteworthy/al-khaser#151]
In " Anti VM -> Generic.cpp -> serial_number_bios_wmi() "

(StrStrI(vtProp.bstrVal, _T("0")) != 0) || // VBox

I think this condition is not good, cause it use StrStr() and there is only 1 character, "0".
Thank you.

**Comment by LordNoteworthy** [comment]
Hello @SanseoLab ,

What do you suggest here ? Let me look into it.

**Comment by gsuberland** [comment]
I was originally going to close this as invalid, under the assumption that @SanseoLab had misunderstood the code, but now I get what they mean. The current check just looks for a `0` character _anywhere_ in the BIOS serial number. This will result in a lot of false positives. I'll change the check to just look for an exact serial of `0`.
