### ISSUE TITLE
QueueUserAPC always terminate without error

### ISSUE THREAD

**Issue by Spiralem** [LordNoteworthy/al-khaser#156]
https://github.com/LordNoteworthy/al-khaser/blob/c1c491df29451837807965f9fb13a50a018c35d9/al-khaser/CodeInjection/QueueUserAPC.cpp#L34-L35

hThread is initialized with `NULL` and have not been reassigned any value, hence program always exit prematurely.

**Comment by LordNoteworthy** [comment]
Thank you for reporting, I will fix it soon.
