### ISSUE TITLE
Bugreport?

### ISSUE THREAD

**Issue by hfiref0x** [LordNoteworthy/al-khaser#157]
Hello,

how do you take bugreports, should I give you patches or you fix it on your own, do you need separate issue for each bug or combined issue post?

Thanks.

**Comment by LordNoteworthy** [comment]
Hey @hfiref0x ,

Would be very helpful if someone would submit a PR to fix the issue, otherwise, we will try ot fix it by our own. 

If the bugs seems to be related sonmehow, you can open one ticket, otherwise a separate issue for each bug.

**Comment by hfiref0x** [comment]
Got it, thanks.
