### ISSUE TITLE
XP support, VMDriverServices

### ISSUE THREAD

**Issue by hfiref0x** [LordNoteworthy/al-khaser#164]
Hello,

coupe of questions I would like to ask:

1) does this program intended to support Windows XP?

If so, it cannot work here because uses function that is missing on Windows XP - EnumProcessModulesEx.

2) The purpose of VMDriverServices routine in Services.cpp
https://github.com/LordNoteworthy/al-khaser/blob/5eea3ff95504c22f3b607d6d4ad35171df0a1efe/al-khaser/AntiVM/Services.cpp#L5

What actually it supposed to detect? VM drivers/services of host or guest? There is no description of this function and it behavior is unclear.

I'm asking because this list

`	const TCHAR* KnownVMServices[KnownServiceCount] = {
		L"VBoxDrv",
		L"VBoxNetAdp",
		L"VBoxNetLwf",
		L"VBoxUSB",
		L"VBoxUSBMon",
		L"VMnetAdapter",
		L"VMnetBridge",
		L"VMnetuserif",
		L"vmusb",
		L"vmx86"
};`

first part contain VirtualBox drivers that are host only. They do not present _inside_ VM. Second part of this list is VMware drivers, but it is little bit old and should include at least this one listed here -> https://usuaria.org.ar/sites/default/files/documentos/1245_SYMANTEC_FIREEYE.pdf However even that list is incomplete and if I look on my vmware I see more values to add (vmusbmouse, vmmemctl, vmx_svga). Should I add it, or  VMDriverServices work as expected?

Thanks.

**Comment by LordNoteworthy** [comment]
Hi @hfiref0x ,

1. Yes, this program is intended to run in Windows XP, as EnumProcessModulesEx is missing in XP, we just skkip this trick which make this API call in XP.

2. It is intended to detect VM drivers/services of the guest, I think instead of looking at my guest, I looked at my host when I picked those drivers for the first time.

Best regards,

**Comment by hfiref0x** [comment]
Hi,

the fix for VM drivers/services is in https://github.com/LordNoteworthy/al-khaser/pull/165 PR.

Kind Regards.
