### ISSUE TITLE
MmMapIoSpace vm detect

### ISSUE THREAD

**Issue by lurumdare** [LordNoteworthy/al-khaser#167]
Maybe write this checks?

Parallels Software
Virtual Machine
VirtualBox
QEMU BIOS
VMware
Bochs

**Comment by gsuberland** [comment]
What specific check are you referring to? MmMapIoSpace is a kernel-mode API, and by policy we don't load drivers as part of al-khaser.

**Comment by LordNoteworthy** [comment]
Hey @lurumdare,

@gsuberland is right about the loading of drivers policy.

I will close the issue, if you have more info about how this check works, you can open it again for the sake of discussion.

**Comment by lurumdare** [comment]
@LordNoteworthy okay. Close it.
