### ISSUE TITLE
hello I can't download

### ISSUE THREAD

**Issue by samdogo** [LordNoteworthy/al-khaser#185]
You can download the latest release here: x86 | x64.
Sorry, binaries have been removed for now as they were triggering Google's Safe Browsing heuristics.

Now I can't use al-khaser?

**Comment by gsuberland** [comment]
Download the source and build it. Visual Studio Community is free and it
should compile with no additional dependencies required.

**Comment by samdogo** [comment]
I recently patched the game using n-protect.
Do not bypass al-Kaiser.
Can you tell me how to bypass?

**Comment by gsuberland** [comment]
Sorry, I have no idea what you're asking here.

**Comment by LordNoteworthy** [comment]
As @gsuberland you can download the source code and build it by yourself.

Or wait until we start using github releases, we will include the binaries (pwd encrypted).
