### ISSUE TITLE
Anti-Sandbox Check - Known hostnames / usernames

### ISSUE THREAD

**Issue by recvfrom** [LordNoteworthy/al-khaser#189]
Some malware will stop executing if it's running on a machine with certain host names and user names, presumably as an anti-sandbox check.  It'd be awesome if al-khaser could have a check for these.

Usernames checked for by Gootkit, from [1]:
```
CurrentUser
Sandbox
```

Hostnames checked for by Gootkit, from [1]:
```
SANDBOX
7SILVIA
```

Usernames checked for by a Trickbot downloader, from [2]: 
```
Emily
HAPUBWS
Hong Lee
IT-ADMIN
Johnson
Miller
milozs
Peter Wilson
timmy
user
```

Hostnames checked for by a Trickbot downloader, from [2]: 
```
HANSPETER-PC
JOHN-PC
MUELLER-PC
WIN7-TRAPS
```

More research will need to be done to know which sandboxes these usernames and hostnames correspond to.  For the ones that we can't definitively tie back to a known sandbox, should these be included in al-khaser?  It's possible those could be the username/hostname of the malware author's test environment, for instance, and isn't technically an anti-sandbox check.

[1] https://www.sentinelone.com/blog/gootkit-banking-trojan-deep-dive-anti-analysis-features/
[2] https://www.bromium.com/deobfuscating-ostap-trickbots-javascript-downloader/

**Comment by Waterman178** [comment]
It’s a bit interesting, I need to study it.

**Comment by recvfrom** [comment]
Usernames checked for by Betabot, from [1]:
```
sand box
malware
maltest
test user
```

[1] https://www.cybereason.com/blog/betabot-banking-trojan-neurevt

**Comment by recvfrom** [comment]
Usernames checked for by Satan, from [4] (not including ones mentioned above):
```
virus
```

[4] https://cofense.com/satan/
