### ISSUE TITLE
GetFileAttributes can‘t find '.sys' files.

### ISSUE THREAD

**Issue by elfbin-2** [LordNoteworthy/al-khaser#201]
The API(GetFileAttributes) can't used to find  '.sys' files in system directory. If do that, GetFileAttributes() would return INVALID_FILE_ATTRIBUTES. So,some function (like vmware_files()) would always return FALSE！

**Comment by LordNoteworthy** [comment]
Good catch again, thanks mate.

GetFileAttributes was not the issue, it was the wow64 fs direction. The ker automatically redirects to SysWow64 folder and ofc the drivers are not found there.

Cheers.
