### ISSUE TITLE
A mistake in ' check_adapter_name()'

### ISSUE THREAD

**Issue by elfbin-2** [LordNoteworthy/al-khaser#202]
'check_adapter_name()' is in Utils.cpp.
In this function，there is a line like this:
`if (StrCmpI(pwszConverted, szName) == 0)`
There should use ‘StrStrI’ instead of   'StrCmpI' .

**Comment by LordNoteworthy** [comment]
Thanks a lot, @elfbin-2.  

Good catch :)
