### ISSUE TITLE
Windows Server 2019 detected as Windows Server 2016 Technical Preview

### ISSUE THREAD

**Issue by Pernat1y** [LordNoteworthy/al-khaser#209]
Just a small bug.
Windows Server 2019 [Version 10.0.17763.1158]) identified as:
[*] You are running: Microsoft Windows Server 2016 Technical Preview  (build 17763) 64-bit

**Comment by LordNoteworthy** [comment]
Hello @Pernat1y 

Can you please take a look at #210  ?

If you can compile code at branch `Noteworthy` and give it a quick run and see what it display now, would be really appreciated.

Cheers.

**Comment by Pernat1y** [comment]
Hello.
Thanks for update. Looks good:
`[*] You are running: Microsoft Windows Server 2019  (build 17763) 64-bit`

**Comment by LordNoteworthy** [comment]
Thanks for checking it out !
