### ISSUE TITLE
[Enhancement] Few more antisandbox tricks by Hexacorn

### ISSUE THREAD

**Issue by hfiref0x** [LordNoteworthy/al-khaser#211]
This maybe interested for you

http://www.hexacorn.com/blog/2020/05/31/a-few-more-anti-sandbox-tricks/

Also there is a good point that you can check if Windows is licensed or not. This can detect some sandboxes.

API
https://docs.microsoft.com/en-us/windows/win32/api/slpublic/nf-slpublic-slisgenuinelocal

Example from google

```
bool IsWindowsGenuine()
{
GUID uid;
RPC_WSTR rpc=(RPC_WSTR)_T(“55c92734-d682-4d71-983e-d6ec3f16059f”);
UuidFromString(rpc,&uid);
SL_GENUINE_STATE state;
SLIsGenuineLocal(&uid,&state,NULL);

if(state==SL_GENUINE_STATE::SL_GEN_STATE_IS_GENUINE)
return true;
return false;
}
```

**Comment by LordNoteworthy** [comment]
Quick check added.

Thanks @hfiref0x for raising this issue 👍 

I will merge it if it looks ok.
