### ISSUE TITLE
How to obtain exe file of this?

### ISSUE THREAD

**Issue by sobuj53** [LordNoteworthy/al-khaser#222]
Hi,
Thank you for this. I want to download the binary, I understand you've reason to remove it but how do I get one?

**Comment by srpape** [comment]
Wouldn't it be possible to just upload the binaries as encrypted zips?

**Comment by BurntDog** [comment]
You have the source, compile it. Get visual studio 2019 community.

**Comment by gsuberland** [comment]
As noted, you need to compile it for yourself using [Visual Studio](https://visualstudio.microsoft.com/). The community edition is free.
