### ISSUE TITLE
[Improvement] ScanForModules does not support managed modules

### ISSUE THREAD

**Issue by 0x11DFE** [LordNoteworthy/al-khaser#234]
title

**Comment by gsuberland** [comment]
Can you be more specific about what isn't supported? Modules loaded into the process should be detected by the existing checks, regardless of whether they're .NET or native DLLs. Is there some specific .NET module enumeration mechanism that's missing?

**Comment by 0x11DFE** [comment]
> Can you be more specific about what isn't supported? Modules loaded into the process should be detected by the existing checks, regardless of whether they're .NET assemblies or native DLLs. Is there some specific .NET module enumeration mechanism that's missing?

Yes while debugging i figured it was not enumerating .NET modules.

**Comment by gsuberland** [comment]
Which of the module checks isn't detecting .NET modules? How are you injecting .NET modules into the process? From what I can see on my end .NET DLLs are being detected just fine.

**Comment by 0x11DFE** [comment]
My bad i got confused i thought it was enumerating the whole system process modules, So i guess it should be an idea for a new component of AntiAnalysis.

**Comment by LordNoteworthy** [comment]
@0x11DFE  What you want to enumerate are not PE Modules but .NET assemblies, which is different right ?

This tool is using native code, therefore you can't expect a .net binary attaching/hijacking it. Assuming it was managed code, then yeah you can list or enumerate assemblies loaded / referenced (like `Assembly.GetReferencedAssemblies()` ) then you can check if the assembly name is in the blacklist.

In addition to that, so if this tool enumerate the list of running processes, and eventually injects a managed dll to a managed process to find out if it has one of the blacklisted assemblies, what would that entails ? it is still not our own process. (it is not like the other anti vm/debug tricks where you can assume if one debugger process is running, then it is a  researcher/malware analyst machine.)

**Comment by gsuberland** [comment]
I'm still confused.

.NET assemblies are regular PE DLLs, and they appear in the results of `EnumProcessModules` when loaded into a process. They should also appear in the results of `NtQuerySystemInformation` when using `SystemModuleInformation`. It doesn't matter whether the host process is managed or native - they're loaded just like any other PE; they just happen to have a .NET metadata table in the PE header that tells the OS that the module needs the CLR. If you load a .NET DLL from disk into the process, it should appear in the process' module list in exactly the same way as any other DLL in a process is.

Are you referring to in-memory assemblies, such as ones loaded by `AppDomain.Load(byte[])`? That would certainly be something we should try to find in the Al-Khazer process memory, although I'm not sure of the best way. Process Hacker appears to use ETW to find .NET assemblies in a process. We'd need to check whether this is supported on non-.NET processes that are injected with dynamic assemblies.

**Comment by 0x11DFE** [comment]
> I'm still confused.
> 
> .NET assemblies are regular PE DLLs, and they appear in the results of `EnumProcessModules` when loaded into a process. They should also appear in the results of `NtQuerySystemInformation` when using `SystemModuleInformation`. It doesn't matter whether the host process is managed or native - they're loaded just like any other PE; they just happen to have a .NET metadata table in the PE header that tells the OS that the module needs the CLR. If you load a .NET DLL from disk into the process, it should appear in the process' module list in exactly the same way as any other DLL in a process is.
> 
> Are you referring to in-memory assemblies, such as ones loaded by `AppDomain.Load(byte[])`? That would certainly be something we should try to find in the Al-Khazer process memory, although I'm not sure of the best way. Process Hacker appears to use ETW to find .NET assemblies in a process. We'd need to check whether this is supported on non-.NET processes that are injected with dynamic assemblies.

Yes exactly they might be loaded from memory since i can only seem to find them using Process Hacker.

**Comment by 0x11DFE** [comment]
> @0x11DFE What you want to enumerate are not PE Modules but .NET assemblies, which is different right ?
> 
> This tool is using native code, therefore you can't expect a .net binary attaching/hijacking it. Assuming it was managed code, then yeah you can list or enumerate assemblies loaded / referenced (like `Assembly.GetReferencedAssemblies()` ) then you can check if the assembly name is in the blacklist.
> 
> In addition to that, so if this tool enumerate the list of running processes, and eventually injects a managed dll to a managed process to find out if the remote process has one of the blacklisted assemblies, what would that entails ? it is still not our own process. (it is not like the other anti vm/debug tricks where you can assume if one debugger process is running in the system, then it is a researcher/malware analyst machine.)

It was just an idea yeah it might have some false positives. But i do think its a better way rather than enumerating all process names and checking if it matches a given blacklist.

**Comment by gsuberland** [comment]
I've just had a look at some injected processes and I think we can detect .NET binaries being loaded into the process without needing to mess around with ETW.

When the CLR is attached to a process, regardless of whether or not it started out as a .NET process, it creates in-memory structures that describe the loaded managed modules. The structures look like this:

```
0000000000000000 0000000000000000 0000000000000000 0000000000000000
0000000000000000 0000000000000000 PPPPPPPPPPPPPPPP 00000000LLLLLLLL
0000000000000001 0000000000000002 0000000000000000 0000000000000002
0000000000000000 0000000000000002
```

Where `PPPPPPPPPPPPPPPP` is a pointer to a UTF-16 string that names the module, and `LLLLLLLL` is the length of that string in bytes.

This data is always present inside a private committed memory region that is 0x20000 bytes in size, with `PAGE_READWRITE` access. An entry should be present for each module that is loaded, regardless of whether the module is loaded from disk or not.

If you want to validate this for yourself, use Cheat Engine to scan an injected process for the following groupscan: `8:0 8:0 8:0 8:0 8:0 8:0 8:* 8:* 8:1 8:2 8:0 8:2 8:0 8:2`.  You can then look in the memory viewer (set the display type to 8 byte hex) and follow the pointer to see the module name strings.

I can implement a check for this using the same approach that our existing memory scanner uses.

**Comment by gsuberland** [comment]
Note: This only works on .NET Framework binaries. Doesn't appear to work for .NET Core / .NET 5.0 stuff, but if the injector stub is .NET Framework based it still catches that. So there's probably more work to be done on this using ETW. But that's a bit of a pain, so probably one for future rather than now.

**Comment by gsuberland** [comment]
There are some restrictions to this. If the target process being scanned is a .NET Core process, it doesn't find anything. But if the target process is a native process (like al-khaser) then it does detect it, even if the assembly being injected is a .NET Core DLL.

It also works if the host process is a managed .NET Framework executable. So it looks like the .NET Core host process doesn't generate these structures, for some reason. But that doesn't cause problems here, since we're only scanning in al-khaser's process memory and that means we catch everything.

**Comment by LordNoteworthy** [comment]
Excellent work @gsuberland 👍 

Regarding the previous discussions about assemblies being show in `EnumProcessModules`. You're absolutely correct,.

If the dll/assembly (let's say dnlib) is referenced directly, then it won't show up in the EnumProcessModules and I was a bit messed up by this.
