### ISSUE TITLE
Is dyncheck.com signature exists?

### ISSUE THREAD

**Issue by Miracle-doctor** [LordNoteworthy/al-khaser#242]
With which technique can detect https://dyncheck.com/ checked?

**Comment by gsuberland** [comment]
No idea. Did you try running Al-Khaser through it to see what the output was?

**Comment by LordNoteworthy** [comment]
@Miracle-doctor write a quick script that run al-khaser and upload the output to a pastebin-like website.

**Comment by Miracle-doctor** [comment]
I understand you. I'll check it

**Comment by LordNoteworthy** [comment]
Closing this issue for now. Let us know if you managed to get the output of the tool here.
