### ISSUE TITLE
Where \Anti Dump\SizeOfImage.h and Anti Dump\SizeOfImage.cpp ?

### ISSUE THREAD

**Issue by Abs0lem8** [LordNoteworthy/al-khaser#34]
Error	1	error C1083: Cannot open source file: 'Anti Dump\SizeOfImage.cpp': No such file or directory	

Error	2	error C1083: Cannot open include file: '..\Anti Dump\SizeOfImage.h': No such file or directory

**Comment by LordNoteworthy** [comment]
Could you try now ? I added the according files.

I will push soon a compiled release.

**Comment by Abs0lem8** [comment]
THX compile 100% ;)
