### ISSUE TITLE
'Anti Debug\SetHandleInformation_API.cpp' 'Anti Debug\SetHandleInformation_API.h'

### ISSUE THREAD

**Issue by elnat** [LordNoteworthy/al-khaser#47]
what about this files, i think thay are need!

**Comment by LordNoteworthy** [comment]
should be fixed now, in the Main.cpp, you can comment/uncomment the tricks you are interestede to :)

**Comment by elnat** [comment]
can you add http://www.rohitab.com/discuss/topic/42453-dype/ this to your code?

**Comment by LordNoteworthy** [comment]
Yep, will add it tonight.

**Comment by LordNoteworthy** [comment]
Interesting, I will open a new ticket and I will add it in the near future, will need to time.
