### ISSUE TITLE
idag and idaq

### ISSUE THREAD

**Issue by R00ke** [LordNoteworthy/al-khaser#57]
Hi, i think this  [https://github.com/LordNoteworthy/al-khaser/blob/master/al-khaser/Anti%20Analysis/process.cpp#L20](url) should be changed to "idaq.exe"

al-khaser/Anti Analysis/process.cpp --> Line 20

**Comment by LordNoteworthy** [comment]
True, I will fix that tonight :) thanks.

**Comment by LordNoteworthy** [comment]
Fixed, gonna be released on the next commit.
