### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by MamuEbal** [LordNoteworthy/al-khaser#69]
Hello.
File: Anti VM/Generic.cpp, variable LPTSTR buffer = NULL; (326) will be allocated if no one StrStrI(buffer succeeded. Put it in function's global namespace and check nor NULL before return.

**Comment by LordNoteworthy** [comment]
Thanks for reporting, gonna be fixed soon !

**Comment by LordNoteworthy** [comment]
#70 is that ok ?

**Comment by LordNoteworthy** [comment]
Thanks a lot !
