### ISSUE TITLE
the al-khaseris not functioning properly

### ISSUE THREAD

**Issue by stonedreamforest** [LordNoteworthy/al-khaser#79]
![2017-06-17_12-20-28](https://user-images.githubusercontent.com/16742566/27250089-d86d17fa-5357-11e7-99fd-0dc540d38681.gif)

**Comment by LordNoteworthy** [comment]
Sorry for my late answer, you mean that you want to hit the BP at the end of the TLS callback routine ?

**Comment by stonedreamforest** [comment]
yes

**Comment by LordNoteworthy** [comment]
Hey @stonedreamforest 

I just repeat that same process of which you had, and my BP are always triggered.

![Attached a screenshot](https://preview.ibb.co/cRtW76/TLS.png).

Can you check again please.

**Comment by LordNoteworthy** [comment]
Ping ?

**Comment by LordNoteworthy** [comment]
I will close the issue, if you still have a problem, feel free to open it again.
