### ISSUE TITLE
port to Qt5

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [LordNoteworthy/al-khaser#84]
port to Qt5 
`process.obj : error LNK2019: unresolved external symbol "void __cdecl print_results(int,wchar_t *)" (?print_results@@YAXHPA_W@Z) referenced in function "void __cdecl analysis_tools_process(void)" (?analysis_tools_process@@YAXXZ)`

**Comment by LordNoteworthy** [comment]
Hello @MrAhmedSayedAli ,

Do you want to port it to Qt5?

Thanks.

**Comment by MrAhmedSayedAli** [comment]
if available

**Comment by MrAhmedSayedAli** [comment]
up

**Comment by LordNoteworthy** [comment]
Hey Ahmed, what are the advantages of porting it to Qt ? 

What are you trying to achieve ?

PS: I do not have any experience with Qt :)

Thank you.

**Comment by LordNoteworthy** [comment]
ping @MrAhmedSayedAli

**Comment by LordNoteworthy** [comment]
At the moment, I don't see any benefits to port this to Qt. If you have any strong reasons, just let me know and feel free to re-open the issue.
