### ISSUE TITLE
Qemu-QA

### ISSUE THREAD

**Issue by kaganisildak** [LordNoteworthy/al-khaser#86]
I think qemu-qa.exe should be added to the "Processes" section

**Comment by LordNoteworthy** [comment]
Hey @kaganisildak 

Sorry for the late answer. Seems it related to Qemu, but I was not able to find out what is the purpose of this process. Google does not show many results. Did you see anywhere on a malware (sha256) or a sandbox system which have this process running ?

Thank you.

**Comment by LordNoteworthy** [comment]
Ping ? :)

**Comment by LordNoteworthy** [comment]
I will close this issue, as regardless of my efforts to find something where this process name could relate to malware, I was not able to find anything useful. Please, let me know if you believe this issue should be opened again.

**Comment by kaganisildak** [comment]
https://any.run/

Any.Run is an amas. It use qemu-qa.exe for monitoring os.

**Comment by LordNoteworthy** [comment]
Seems it is qemu-**g**a not qemu-**q**a  ?
