### ISSUE TITLE
Precompiled 32 bit binary

### ISSUE THREAD

**Issue by s3c** [LordNoteworthy/al-khaser#87]
Precompiled 32 bit binary would be nice, just a thought.

**Comment by LordNoteworthy** [comment]
Will be added on the next commit, thanks for the suggestion.

**Comment by sioban** [comment]
Hi,
Nothing new about a 32 bit version ?

**Comment by LordNoteworthy** [comment]
You can check now, I just compiled a 32bit version. Feel free to close the issue if it matches your expectation.

**Comment by s3c** [comment]
Awesome, thanks a bunch
