### ISSUE TITLE
#bug ascii_to_wide_str maybe have a malloc issues

### ISSUE THREAD

**Issue by stxletto** [LordNoteworthy/al-khaser#94]
TCHAR* ascii_to_wide_str(CHAR* lpMultiByteStr)
{

	/* Get the required size */
	CONST INT iSizeRequired = MultiByteToWideChar(CP_ACP, 0, lpMultiByteStr, -1, NULL, 0);

	TCHAR *lpWideCharStr = (TCHAR*)MALLOC(**iSizeRequired** * sizeof(TCHAR));

	/* Do the conversion */
	INT iNumChars =  MultiByteToWideChar(CP_ACP, 0, lpMultiByteStr, -1, lpWideCharStr, iSizeRequired);

	return lpWideCharStr;
}

**Comment by LordNoteworthy** [comment]
Hey Stxletto :)

👍  for the gotcha !

Here is a PR to fix that: #96 .

Give me your OK if it solves the issue so I can close it .

**Comment by LordNoteworthy** [comment]
Closed, feel free to re-open it if you see any problem.
