### ISSUE TITLE
#bug process.cpp line 23 and 28 is same

### ISSUE THREAD

**Issue by stxletto** [LordNoteworthy/al-khaser#95]
_T("dumpcap.exe"),			// Network traffic dump tool
		_T("HookExplorer.exe"),		// Find various types of runtime hooks
		_T("ImportREC.exe"),		// Import Reconstructor
		_T("PETools.exe"),			// PE Tool
		_T("LordPE.exe"),			// LordPE
		**//_T("dumpcap.exe"),		// same with line 23**

**Comment by LordNoteworthy** [comment]
Corrected, thanks a lot !
