### ISSUE TITLE
Got a Question

### ISSUE THREAD

**Issue by Lilantboy** [LordNoteworthy/al-khaser#97]
How did you learn to use the functions in the windows.h file ?

**Comment by LordNoteworthy** [comment]
You mean the Win32 APIs ?

**Comment by LordNoteworthy** [comment]
If you are talking about the Win32API, I recommand Windows 95 Programming by Charle Petzold:
https://www.amazon.com/Programming-Windows-95-Microsoft/dp/1556156766

Even if it is an old book, it is still valid and very relevant. You can download the examples here: http://www.charlespetzold.com/src/ProgWin5.zip

Also: Windows via C/C++ 5th Edition
https://www.amazon.com/Windows-via-Jeffrey-M-Richter/dp/0735624240/ref=sr_1_13?ie=UTF8&qid=1515413091&sr=8-13&keywords=windows+programming

It shows you how to work with Windows APIs with C/C++. Maybe you wanna look at this one first.

I will close the issue, if you have any questions, feel free to open it again.
