### ISSUE TITLE
FirmwareACPI/SMBIOS for Qemu/VMWare

### ISSUE THREAD

**Issue by wooddii** [LordNoteworthy/al-khaser#98]
Hello, add to the FirmwareACPI function a validation of known virtual machines:
-VMWare:
                       PBYTE vmwString = (PBYTE)"VMW";
			size_t vmwStringLen = 3;
			PBYTE vmwareUpperString = (PBYTE)"VMWARE";
			size_t vmwareUpperStringLen = 6;

			if (find_str_in_data(vmwString, vmwStringLen, table, tableSize) ||
				find_str_in_data(vmwareUpperString, vmwareUpperStringLen, table, tableSize)) {
				result = TRUE;
			}
-QEMU:
			PBYTE bxpString = (PBYTE)"BXP";
			size_t bxpStringLen = 3;
			PBYTE bochsUpperString = (PBYTE)"BOCHS";
			size_t bochsUpperStringLen = 5;

			if (find_str_in_data(bxpString, bxpStringLen, table, tableSize) ||
				find_str_in_data(bochsUpperString, bochsUpperStringLen, table, tableSize)) {
				result = TRUE;
			}

It can also be useful trick with checking MSR. The value of most of them in the virtual machine is zero,while on the real - no.  But this requires a driver, for example, I used the AsIO.sys like this:

```
void getMSRValue(DWORD reg, DWORD64 *val) {
	if (drvHandle == NULL) { return; }
	DWORD dwBytes;
	if (DeviceIoControl( drvHandle, 0x0a0406458, &reg, sizeof(DWORD),
					val, sizeof(DWORD64), &dwBytes, NULL) == NULL) { 								 
                       printf("DeviceIoControl error: %d\n", GetLastError()); 	
        }
}
```

PC:
![pc](https://user-images.githubusercontent.com/35064537/34580923-b5f9c1be-f19f-11e7-99ae-919d4b43e797.jpg)

VBox:
![virtualbox](https://user-images.githubusercontent.com/35064537/34580926-b62537f4-f19f-11e7-8a71-80ae641824e7.jpg)

VMWare:
![vmware](https://user-images.githubusercontent.com/35064537/34581228-c0c1adfe-f1a0-11e7-8e5b-48803e2bd7ac.jpg)

Thanks!

**Comment by LordNoteworthy** [comment]
Interesting ! Thanks a lot @wooddii , I will make a PR in tomorrow.

**Comment by LordNoteworthy** [comment]
Added the firmware tables checks for VMWare, will add soon the ones of Qemu.

**Comment by gsuberland** [comment]
@LordNoteworthy This appears to have been done (qemu_firmware_ACPI function in Qemu.cpp) although the name in the code is "BXPC" rather than "BXP" as specified by @wooddii above.

@wooddii Despite the obvious merits, I don't think we'll end up doing MSR checks due to the requirement of loading a driver. There are licensing concerns around shipping the Asus drivers and, ultimately, I don't think we should be loading known-vulnerable stuff into the kernel. We could roll our own but then that runs into signing issues, which is a real headache.

**Comment by wooddii** [comment]
@LordNoteworthy , yes, this is particularly difficult to operate, but this can be seen as a potential method.
One more thing, why do not you use assembler tricks (for example, jump to the middle of the instruction) to bypass debugging and dumping?

**Comment by gsuberland** [comment]
@wooddii I'll open a new issue to add that feature.

**Comment by gsuberland** [comment]
@wooddii Actually, having thought about it a bit more, I'm not sure how that would work as a check. Jumping to the middle of instructions is generally an anti-analysis trick. We could certainly do some middle-of-instruction tricks in a function somewhere that does nothing interesting, with the goal of testing heuristic detection, but I don't think we can do much in the way of a concrete pass/fail check at runtime. If you have an idea about how a check might be done at runtime, please open another issue to discuss it.

**Comment by LordNoteworthy** [comment]
> @LordNoteworthy This appears to have been done (qemu_firmware_ACPI function in Qemu.cpp) although the name in the code is "BXPC" rather than "BXP" as specified by @wooddii above. Does this need to be changed?

In my tests, I found out that the string is __BXPC__ rather than __BXP__. Do you confirm @wooddii ?

> @wooddii Despite the obvious merits, I don't think we'll end up doing MSR checks due to the requirement of loading a driver. There are licensing concerns around shipping the Asus drivers and, ultimately, I don't think we should be loading known-vulnerable stuff into the kernel. We could roll our own but then that runs into signing issues, which is a real headache.

I agree with @gsuberland.

**Comment by LordNoteworthy** [comment]
Thanks @wooddii for the feedback ! I will close this issue for now, if you are interested to discuss the anti-analysis trick mentioned above, feel free to open a new ticket and we can discuss it.
